/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Datos.Archivos;
import Negociacion.Imagenes;
import Negociacion.NBaraja;
import Objetos.Baraja;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatAtomOneDarkIJTheme;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.UIManager;

/**
 *
 * @author Guerrero
 */
public class CardsGameMain extends javax.swing.JFrame {
private Archivos data = new Archivos();
private Imagenes img = new Imagenes();
private NBaraja BRJ = new NBaraja();
private ArrayList<Baraja> BarajaL = new ArrayList();
private ArrayList<Baraja> Jugador = new ArrayList();
private ArrayList<Baraja> PC = new ArrayList();
private HashMap PD = new HashMap();
private ArrayList<JLabel> LabelPlayer = new ArrayList<>();
private ArrayList<JLabel> LabelPC = new ArrayList<>();

/**
     * Creates new form CardsGameMain
     */
    public CardsGameMain() {
        initComponents();
        loadCardz();//carga la baraja, el print esta ajustado para solo mostrar uno
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        MenuBar = new javax.swing.JMenuBar();
        Inicio = new javax.swing.JMenu();
        BtnBack = new javax.swing.JMenuItem();
        TestButton = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cartas Inglesas Super Divertidas");
        setSize(new java.awt.Dimension(400, 300));

        jButton1.setText("Jugar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Inicio.setText("Inicio");

        BtnBack.setText("Volver");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });
        Inicio.add(BtnBack);

        TestButton.setText("TestButton");
        TestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TestButtonActionPerformed(evt);
            }
        });
        Inicio.add(TestButton);

        MenuBar.add(Inicio);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(710, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(207, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        MenuPrincipal mgame = new MenuPrincipal();
        mgame.setVisible(true);
        mgame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_BtnBackActionPerformed

    private void loadCardz(){
        try {
        data.loadCards();
        BRJ.definirPalos();
        BarajaL = BRJ.getList(); //Cuando se implemente la funcion de revolver, se deberia llamar en esta linea
        Jugador = BRJ.repartir(BarajaL);
        BarajaL.removeAll(Jugador);
        PC = BRJ.repartir(BarajaL);
        BarajaL.removeAll(PC);
        JLabel bckbrj = new JLabel();
        bckbrj.setIcon(img.getScaledImage(new ImageIcon("files/BRJ/BCKBRJ.png"), 80, 100));
        bckbrj.setBounds(10, 175, 80, 100);
        this.add(bckbrj);
            for (int i = 0; i < Jugador.size(); i++) {
                Baraja get = Jugador.get(i);
                JLabel label = new JLabel();
                label.setIcon(get.getImg());
                LabelPlayer.add(label);
            }
            for (int j = 0; j < LabelPlayer.size(); j++) {
                JLabel getLa = LabelPlayer.get(j);
                getLa.setBounds(50 + (70*j), 350, 65, 100);
                this.add(getLa);
                
            }
            for (int r = 1; r < (PC.size()+1); r++) {
                JLabel label = new JLabel();
                label.setIcon(img.getScaledImage(new ImageIcon("files/BRJ/BCK (" + r + ").png"), 65, 100));
                LabelPC.add(label);
            }
            for (int j = 0; j < LabelPC.size(); j++) {
                JLabel getL = LabelPC.get(j);
                getL.setBounds(70 + (70*j), 10, 65, 100);
                this.add(getL);
                
            }
            PD = BRJ.getPalos();
            
    } catch (FileNotFoundException ex) {
        
    } 
    }
    
    
    private void comparar() {
        for (int i = 0; i < 10; i++) {
            Baraja Carta = PC.get(i);
            JLabel label = LabelPC.get(i);
            label.setIcon(Carta.getImg());
            Baraja Carta2 = Jugador.get(i);
            logica(Carta, Carta2);
        }
    }
    
    private void logica(Baraja cd1, Baraja cd2) {
        String name1 = cd1.getNcardname();
        String name2 = cd2.getNcardname();
        int num1 = Integer.valueOf(cd1.getNcardnumber());
        int num2 = Integer.valueOf(cd2.getNcardnumber());
        String tipo1 = PD.get(cd1.getNcardname()).toString();
        String tipo2 = PD.get(cd2.getNcardname()).toString();
        if (name1.equals(name2)) {
            System.out.println(num1 + "," + num2);
            if(num1 < num2) {
                System.out.println("gana" + cd1);
            } else {
                System.out.println("gana" + cd2);
            }
        } else if (tipo1.equals(tipo2)) {
            if(num1 < num2) {
                System.out.println("gana" + cd1);
            } else {
                System.out.println("gana" + cd2);
            }
        } else if (tipo1.equals("Fuerte") && tipo2.equals("Regular")||tipo2.equals("Fuerte") && tipo1.equals("Regular")) {
            if(tipo1.equals("Fuerte")) {
                System.out.println("gana" + cd1);
            } else {
                System.out.println("gana" + cd2);
            }
        } else if (tipo1.equals("Debil") && tipo2.equals("Regular")||tipo2.equals("Debil") && tipo1.equals("Regular")) {
            if(tipo1.equals("Regular")) {
                System.out.println("gana" + cd1);
            } else {
                System.out.println("gana" + cd2);
            }
        } else if (tipo1.equals("Debil") && tipo2.equals("Fuerte")||tipo2.equals("Debil") && tipo1.equals("Fuerte")) {
            if(tipo1.equals("Debil")) {
                System.out.println("gana" + cd1);
            } else {
                System.out.println("gana" + cd2);
            }
        }
    }
    
    private void TestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TestButtonActionPerformed
        loadCardz();
    }//GEN-LAST:event_TestButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     comparar();   // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try{
            UIManager.setLookAndFeel(new FlatAtomOneDarkIJTheme());
        } catch (Exception e){
            e.printStackTrace();
        }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatAtomOneDarkIJTheme".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CardsGameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CardsGameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CardsGameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CardsGameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CardsGameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BtnBack;
    private javax.swing.JMenu Inicio;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem TestButton;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
