/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Negociacion.PieChartDiamond;
import Datos.Archivos;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatAtomOneDarkIJTheme;
import java.awt.Color;
import java.io.FileNotFoundException;
import javax.swing.JFrame;
import javax.swing.UIManager;

/**
 *
 * @author Guerrero
 */
public class FrmPuntu extends javax.swing.JFrame {
private Archivos data = new Archivos();
    /**
     * Creates new form NewJFrame
     */
    public FrmPuntu() {
        initComponents();
        TRLoad();
    }

    void TRLoad(){
        data.loadList();
        RecordsTable.setModel(data.RecordsTablez);
        RecordsTable.getTableHeader().getColumnModel().getColumn(0).setHeaderRenderer(data.MyHeaderRender);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        RecordsTable = new javax.swing.JTable();
        MenuBar = new javax.swing.JMenuBar();
        Inicio = new javax.swing.JMenu();
        BtnDiamGraphs = new javax.swing.JMenuItem();
        BtnPicGraphs = new javax.swing.JMenuItem();
        BtnCoraGraphs = new javax.swing.JMenuItem();
        BtnTrebGraphs = new javax.swing.JMenuItem();
        BtnBack = new javax.swing.JMenuItem();
        TestButton = new javax.swing.JMenuItem();

        setTitle("Puntuaciones");
        setSize(new java.awt.Dimension(600, 400));

        RecordsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        RecordsTable.setColumnSelectionAllowed(true);
        RecordsTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(RecordsTable);
        RecordsTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        Inicio.setText("Menu");

        BtnDiamGraphs.setText("Porcentaje Diamantes");
        BtnDiamGraphs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDiamGraphsActionPerformed(evt);
            }
        });
        Inicio.add(BtnDiamGraphs);

        BtnPicGraphs.setText("Porcentaje Picas");
        BtnPicGraphs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPicGraphsActionPerformed(evt);
            }
        });
        Inicio.add(BtnPicGraphs);

        BtnCoraGraphs.setText("Porcentaje Corazones");
        BtnCoraGraphs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCoraGraphsActionPerformed(evt);
            }
        });
        Inicio.add(BtnCoraGraphs);

        BtnTrebGraphs.setText("PorcentajeTreboles");
        BtnTrebGraphs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTrebGraphsActionPerformed(evt);
            }
        });
        Inicio.add(BtnTrebGraphs);

        BtnBack.setText("Volver");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });
        Inicio.add(BtnBack);

        TestButton.setText("TestButton");
        TestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TestButtonActionPerformed(evt);
            }
        });
        Inicio.add(TestButton);

        MenuBar.add(Inicio);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        MenuPrincipal mgame = new MenuPrincipal();
        mgame.setVisible(true);
        mgame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_BtnBackActionPerformed

    private void BtnDiamGraphsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDiamGraphsActionPerformed
        PieChartDiamond CC = new PieChartDiamond("Gráfico","Porcentaje de Diamantes");        
        CC.pack();        
        CC.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        CC.setVisible(true);  
        CC.setTitle("Porcentaje de Diamantes");
        CC.setLocationRelativeTo(null);
    }//GEN-LAST:event_BtnDiamGraphsActionPerformed

    private void TestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TestButtonActionPerformed
    try {
        data.loadCards();
    } catch (FileNotFoundException ex) {
        
    }  
    }//GEN-LAST:event_TestButtonActionPerformed

    private void BtnTrebGraphsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTrebGraphsActionPerformed
        PieChartDiamond CC = new PieChartDiamond("Gráfico","Porcentaje de Treboles");        
        CC.pack();        
        CC.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        CC.setVisible(true);
        CC.setTitle("Porcentaje de Treboles");       
        CC.setLocationRelativeTo(null);
    }//GEN-LAST:event_BtnTrebGraphsActionPerformed

    private void BtnCoraGraphsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCoraGraphsActionPerformed
        PieChartDiamond CC = new PieChartDiamond("Gráfico","Porcentaje de Corazones");        
        CC.pack();        
        CC.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        CC.setVisible(true); 
        CC.setTitle("Porcentaje de Corazones");
        CC.setLocationRelativeTo(null);
    }//GEN-LAST:event_BtnCoraGraphsActionPerformed

    private void BtnPicGraphsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPicGraphsActionPerformed
        PieChartDiamond CC = new PieChartDiamond("Gráfico","Porcentaje de Picas");        
        CC.pack();        
        CC.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        CC.setVisible(true); 
        CC.setTitle("Porcentaje de Picas");
        CC.setLocationRelativeTo(null);
    }//GEN-LAST:event_BtnPicGraphsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try{
            UIManager.setLookAndFeel(new FlatAtomOneDarkIJTheme());
        } catch (Exception e){
            e.printStackTrace();
        }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatAtomOneDarkIJTheme".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPuntu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPuntu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPuntu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPuntu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPuntu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BtnBack;
    private javax.swing.JMenuItem BtnCoraGraphs;
    private javax.swing.JMenuItem BtnDiamGraphs;
    private javax.swing.JMenuItem BtnPicGraphs;
    private javax.swing.JMenuItem BtnTrebGraphs;
    private javax.swing.JMenu Inicio;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JTable RecordsTable;
    private javax.swing.JMenuItem TestButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
